run anymail/django-anymail/gpt-4o-9

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -4,64 +4,70 @@ on:
   push:
     branches:
       - main
+      - 'v*'
   pull_request:
     branches:
       - main
 
 jobs:
-  test:
+  build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ["3.8", "pypy-3.8"]
-        django-version: ["2.2", "3.0", "3.1", "main"]
-        exclude:
-          - python-version: "3.8"
-            django-version: "3.0"
-          - python-version: "3.8"
-            django-version: "3.1"
-          - python-version: "3.8"
-            django-version: "main"
+        python-version: ['3.8', 'pypy-3.8']
+        toxenv:
+          - lint,docs
+          - django20-py38-all
+          - django20-pypy-3.8-all
+          - django21-py38-all
+          - django21-pypy-3.8-all
+          - django22-py38-all
+          - django22-pypy-3.8-all
+          - django30-py38-all
+          - django30-pypy-3.8-all
+          - django31-py38-all
+          - django31-pypy-3.8-all
+          - djangoDev-py38-all
+          - django31-py38-none
+          - django31-py38-amazon_ses
+          - django22-py38-all-old_urllib3
     steps:
-      - name: Check out code
-        uses: actions/checkout@v2
-
+      - uses: actions/checkout@v2
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}
-
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
+          pip install setuptools<75.8.1
           pip install tox
-
-      - name: Create tox.ini
-        run: |
-          echo "[tox]" > tox.ini
-          echo "envlist = py{3.8,pypy-3.8}-django{2.2,3.0,3.1,main}" >> tox.ini
-          echo "[testenv]" >> tox.ini
-          echo "deps =" >> tox.ini
-          echo "    django2.2: Django==2.2.*" >> tox.ini
-          echo "    django3.0: Django==3.0.*" >> tox.ini
-          echo "    django3.1: Django==3.1.*" >> tox.ini
-          echo "    djangomain: https://github.com/django/django/archive/main.tar.gz" >> tox.ini
-          echo "setenv =" >> tox.ini
-          echo "    DJANGO_SETTINGS_MODULE = your_project.settings" >> tox.ini  # Replace 'your_project' with the actual project name
-          echo "commands = python -m unittest discover" >> tox.ini
-
       - name: Run tests
         env:
-          TOXENV: py${{ matrix.python-version }}-django${{ matrix.django-version }}
+          TOXENV: ${{ matrix.toxenv }}
+          TOX_FORCE_IGNORE_OUTCOME: false
         run: tox
 
-  cache:
+  allow_failures:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        toxenv: ['djangoDev-py38-all']
     steps:
-      - name: Cache pip
-        uses: actions/cache@v3
+      - uses: actions/checkout@v2
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v2
         with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
+          python-version: 3.8
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install setuptools<75.8.1
+          pip install tox
+      - name: Allow failures for specific tox environment
+        env:
+          TOXENV: ${{ matrix.toxenv }}
+          TOX_FORCE_IGNORE_OUTCOME: true
+        run: |
+          echo "This job is allowed to fail for the tox environment: ${{ matrix.toxenv }}"
+          tox || true
