run pavdmyt/yaspin/gpt-4o-9

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,55 +12,71 @@ jobs:
   test:
     runs-on: ubuntu-latest
     strategy:
-      fail-fast: false
       matrix:
-        python-version: ["3.8", "3.9", "3.10"]
-        toxenv:
-          - flake8
-          - check_rst
-          - coverage
-          - py38-django111
-          - py38-django22
-          - py39-django22
-          - py39-django32
-          - py310-django32
-          - py310-django40
-          - py310-django41
+        python-version: ["3.8", "3.9"]
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
+      - uses: actions/checkout@v2
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}
-
-      - name: Cache pip
-        uses: actions/cache@v3
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
-
-      - name: Cache tox
-        uses: actions/cache@v3
-        with:
-          path: .tox
-          key: ${{ runner.os }}-tox-${{ hashFiles('**/tox.ini') }}
-          restore-keys: |
-            ${{ runner.os }}-tox-
-
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install tox
-
+          pip install --no-deps -r requirements.txt
       - name: Run tests
         env:
-          TOX_ENV: ${{ matrix.toxenv }}
-        run: tox -e $TOX_ENV
+          PYTHONWARNINGS: "ignore::DeprecationWarning"
+        run: |
+          if [ -f "Makefile" ]; then
+            make ci
+          else
+            echo "Makefile not found, running default test command"
+            pytest --maxfail=1 --disable-warnings || exit 1
+          fi
 
-      - name: Upload tox logs
-        if: failure()
-        run: cat .tox/${{ matrix.toxenv }}/log/*.log
+  test-pypy:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set up PyPy
+        uses: actions/setup-python@v2
+        with:
+          python-version: "pypy-3.8"
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install termcolor==1.1.0 pytest==6.2.4 pytest-xdist==2.3.0
+      - name: Run tests
+        env:
+          PYTHONWARNINGS: "ignore::DeprecationWarning"
+        run: |
+          pytest --maxfail=1 --disable-warnings || exit 1
+
+  coverage:
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set up Python 3.9
+        uses: actions/setup-python@v2
+        with:
+          python-version: "3.9"
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install --no-deps -r requirements.txt
+      - name: Run coverage
+        env:
+          PYTHONWARNINGS: "ignore::DeprecationWarning"
+        run: |
+          if [ -f "Makefile" ]; then
+            make coverage
+          else
+            echo "Makefile not found, running default coverage command"
+            pytest --cov=. --maxfail=1 --disable-warnings || exit 1
+          fi
+      - name: Upload coverage to Codecov
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: bash <(curl -s https://codecov.io/bash)
